apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: petclinic-db
spec:
  serviceName: petclinic-db
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-db
  template:
    metadata:
      labels:
        app: petclinic-db
    spec:
      containers:
        - name: postgres
          image: postgres
          envFrom:
            - secretRef:
                name: petclinic-db-secret
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: petclinic-db-pvc