apiVersion: v1
kind: Secret
metadata:
  name: petclinic-secret
type: Opaque
stringData:
  SPRING_PROFILES_ACTIVE: postgres
  SPRING_DATASOURCE_URL: jdbc:postgresql://petclinic-db:5432/petclinic
  SPRING_DATASOURCE_USERNAME: petclinic
  SPRING_DATASOURCE_PASSWORD: petclinic