apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: petclinic
          image: vhmds/petclinic:v0
          envFrom:
            - secretRef:
                name: petclinic-secret
          ports:
            - containerPort: 8080