apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64  # or arm64 depending on your platform
      containers:
        - name: petclinic
          image: vhmds/petclinic:v0-multiarch  # use a new tag for the multi-arch image
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health/liveness
          #     port: 8080
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health/readiness
          #     port: 8080
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          envFrom:
            - secretRef:
                name: petclinic-secret
          ports:
            - containerPort: 8080